[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[manager.prepend_keymap]]
on = ["z", "h"]
run = "plugin time-travel prev"
desc = "Go to previous snapshot"

[[manager.prepend_keymap]]
on = ["z", "l"]
run = "plugin time-travel next"
desc = "Go to next snapshot"

[[manager.prepend_keymap]]
on = ["z", "e"]
run = "plugin time-travel exit"
desc = "Exit browsing snapshots"

[[manager.prepend_keymap]]
on = [ "<C-w>" ]
run = "plugin close-and-restore-tab close_to_left"
desc = "Close the current tab and turn to left tab, or quit if it is last tab"

[[manager.prepend_keymap]]
on = [ "<C-w>" ]
run = "plugin close-and-restore-tab close_to_right"
desc = "Close the current tab and turn to right tab, or quit if it is last tab"

[[manager.prepend_keymap]]
on = [ "<C-t>" ]
run = "plugin close-and-restore-tab restore"
desc = "Restore the closed tab"

[[manager.prepend_keymap]]
on = "<C-z>"
run = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on = [ "<C-r>" ] 
run = "plugin recycle-bin"
desc = "Open Recycle Bin"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = [ "c", "p" ]
run  = "plugin command"
desc = "Open command palette"
