format = """
[ ](bg:inverted fg:#bf616a)\
$username\
[](bg:#d08770 fg:#bf616a)\
$directory\
[](fg:#d08770 bg:#ebcb8b)\
$git_branch\
$git_status\
[](fg:#ebcb8b bg:#86BBD8)\
$c\
$golang\
$rust\
[](fg:#86BBD8 bg:#5e81ac)\
$character\
$time\
[ ](fg:#5e81ac)\
"""

right_format = """
$cmd_duration\
"""
continuation_prompt = '▶▶ '
# Disable the blank line at the start of the prompt
add_newline = false

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#bf616a bold"
style_root = "bg:#bf616a bold"
format = '[$user]($style)'

[hostname]
style = "bg:#bf616a bold"
format = '[@$hostname ]($style)'
ssh_only = false
disabled = false

[directory]
style = "bg:#d08770 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ebcb8b bold fg:#bf616a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ebcb8b bold fg:#bf616a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M %P" # Hour:Minute Format
style = "bg:#5e81ac bold"
# format = '[ ♥ $time ]($style)'
format = '[$time ]($style)'

[character]
disabled = false
success_symbol = "[ ♥ ](bg:#5e81ac)"
error_symbol = "[ ✖ ](bg:#5e81ac)"
# format = '[ ♥ $time ]($style)'
format = "$symbol"

[jobs]
symbol = '+ '
number_threshold = 4
symbol_threshold = 0
